CREATE TABLE spaces (
  id      INTEGER PRIMARY KEY,
  name    VARCHAR(255) NOT NULL UNIQUE,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE planets (
  id      INTEGER PRIMARY KEY,
  name    VARCHAR(255) NOT NULL UNIQUE,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE islands (
  id      INTEGER PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resource_defs (
  id          INTEGER PRIMARY KEY,
  planet_id   INTEGER NOT NULL,
  created     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated     DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attr_defs (
  id          INTEGER PRIMARY KEY,
  resource_def_id INTEGER NOT NULL,
  key         VARCHAR(255) NOT NULL,
  value       TEXT NOT NULL,
  created     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated     DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE resources (
  id          INTEGER PRIMARY KEY,
  island_id   INTEGER NOT NULL,
  created     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated     DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attrs (
  id          INTEGER PRIMARY KEY,
  resource_id INTEGER NOT NULL,
  key         VARCHAR(255) NOT NULL,
  value       TEXT NOT NULL,
  created     DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated     DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comets (
  id      INTEGER PRIMARY KEY,
  value   TEXT NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- - planet
-- - island ... name, content, tags, resources
-- - comet ... trash or memo
