// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbq

import (
	"database/sql"
)

type Space struct {
	ID      int64
	Name    string
	Created sql.NullTime
	Updated sql.NullTime
}
