// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbq

import (
	"database/sql"
)

type History struct {
	ID       int64
	Resource string
	Comment  string
	Created  sql.NullTime
	Updated  sql.NullTime
}

type Island struct {
	ID         int64
	ResourceID string
	Title      string
	Content    string
	Comment    string
	Created    sql.NullTime
	Updated    sql.NullTime
}

type Pattern struct {
	ID         int64
	ResourceID string
	Title      string
	Priority   sql.NullInt64
	Created    sql.NullTime
	Updated    sql.NullTime
}

type Planet struct {
	ID         int64
	ResourceID string
	Name       string
	Comment    string
	Created    sql.NullTime
	Updated    sql.NullTime
}

type Stone struct {
	ID         int64
	ResourceID string
	PatternID  sql.NullInt64
	IslandID   sql.NullInt64
	Data       string
	Created    sql.NullTime
	Updated    sql.NullTime
}

type Tag struct {
	ID       int64
	Resource string
	Key      string
	Value    string
	Created  sql.NullTime
	Updated  sql.NullTime
}

type Trait struct {
	ID           int64
	ResourceID   string
	PatternID    int64
	Path         string
	Type         string
	DefaultValue string
	Required     bool
	Created      sql.NullTime
	Updated      sql.NullTime
}
